### ISSUE TITLE
Stricter vendor email validation

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/lazona_connector#66]
We just found Koiki's API was complining with `El email del remitente es obligatorio,` because the request specified `'emailRemi': 'serveis@artijoc.com, botiga@artijoc.com'`. This is why :point_down: 

![Screenshot from 2021-05-17 12-06-42](https://user-images.githubusercontent.com/762088/118472128-c6ed6480-b708-11eb-9518-abb91dbfe68e.png)

I believe that the earlier we can catch these validation errors the better.

**Comment by numeropi** [comment]
![image](https://user-images.githubusercontent.com/56868560/122206269-7866ed80-cea1-11eb-84e7-0dc93c180e25.png)

Koiki's API is returning the same error when the email is empty, so I think a better option could be to just use the vendor's WP user email which is mandatory and unique always.
